---
services:
  redis:
    image: redis:8.0-M03-alpine3.21
    container_name: redis
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 6379:6379
    volumes:
      - /data/music-explorer/redis:/data

